name: Run Unit Test via Pytest N
  
on: [push]  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:  
        python-version: ["3.12"]
  
    steps:  
      - uses: actions/checkout@v3  
      - name: Set up Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v4  
        with:  
          python-version: ${{ matrix.python-version }}  
      - name: Run docker-compose  
        run: |  
          docker-compose up -d
      - name: Wait for the service to be ready
        run: | # Add wait strategy here, e.g., wait-for-it.sh or a custom script
          wait-for-it.sh service-name:port --timeout=60 --strict -- echo "Service is up"
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip
          pip install -r bookstore/requirements.txt  
          pip install -U coverage
          pip install pytest
      - name: Lint with Ruff  
        run: |  
          pip install ruff  
          ruff --format=github --target-version=py312  
        continue-on-error: true  
      - name: Test with pytest  
        run: |  
          coverage run -m pytest  -v -s  
      - name: Generate Coverage Report  
        run: |  
          coverage report -m
